#!/bin/sh -f
#
#$ -S /bin/bash
#
# our name 
#$ -N fish
#
# pe request
#$ -pe MPI.all 8-8
#
# MPIR_HOME from submitting environment
#$ -v MPIR_HOME=/soft/mpich,SGE_QMASTER_PORT
# ---------------------------

echo "Got $NSLOTS slots."
source /soft/env/env_64.sh

# enables $TMPDIR/rsh to catch rsh calls if available
export path=($TMPDIR $path)
export PATH="$TMPDIR:${PATH}"

cd /home/liebend/supernovahp2c/
mpirun -machinefile $TMPDIR/machines -np $NSLOTS ./fish
